### ISSUE TITLE
[Bug]: Weapons not included in set bonuses

### ISSUE THREAD

**Issue by JakeBat-H** [magemonkeystudio/divinity#169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Weapons/shields (offhand and mainhand) do not count for a set bonus in game while equipped.

### Expected Behavior

Weapons/shields (offhand and mainhand) should be able to count towards the set bonus.

### Environment

```markdown
- Server Software:
- ProRPGItems Version:
- ProMCCore Version:
- Plugins:
```

**Comment by Travja** [comment]
I'm going to go ahead and close this as after testing this out (finally), I am seeing that weapons are indeed counting toward set bonuses.

![Image](https://github.com/user-attachments/assets/f9cb4a2e-596c-4750-b094-c7b08fc9fc29)

![Image](https://github.com/user-attachments/assets/79ec4694-8f70-43fd-8a56-ce2f007965a2)

```yaml
name: '&eWild Cat Set'
prefix: '&a&fBroken '
suffix: 'of Wild Cat'
color:
  active: '&a'
  inactive: '&8'
elements:
  helmet:
    materials:
      - GOLDEN_HELMET
    name: '%prefix%Helmet %suffix%'
  chestplate:
    materials:
      - GOLDEN_CHESTPLATE
    name: '%prefix%Chestplate %suffix%'
  leggings:
    materials:
      - GOLDEN_LEGGINGS
    name: '%prefix%Leggings %suffix%'
  boots:
    materials:
      - GOLDEN_BOOTS
    name: '%prefix%Boots %suffix%'
  weapon:
    materials:
      - GOLDEN_SWORD
    name: '%prefix%Sword %suffix%'
bonuses:
  by-elements-amount:
    '2':
      lore:
        - '%c%&lSet Bonuses (2/4):'
        - '%c%▸ +25% PvE Damage'
        - '%c%▸ +10 Max. Health'
        - '%c%▸ Speed I'
      item-stats:
        MAX_HEALTH: 10.0
        PVE_DAMAGE: 25
      damage-types: { }
      defense-types: { }
      potion-effects:
        SPEED: 1
```
